---
- name: Vérifier si le paquet Wazuh est déjà installé
  hosts: all
  tasks:
    - name: Vérifier la présence du paquet Wazuh Agent (Linux)
      stat:
        path: /var/ossec/etc/ossec-init.conf  # Choisir un fichier ou un répertoire caractéristique de l'installation de Wazuh
      register: wazuh_installed_linux
      ignore_errors: yes

- name: Déployer l'agent Wazuh
  hosts: all
  tasks:
    - name: Télécharger et installer le paquet Wazuh Agent (Linux)
      when: ansible_facts['os_family'] == 'Debian' and wazuh_installed_linux.stat.exists == false
      become: yes
      shell: |
        wget https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.7.2-1_amd64.deb &&
        WAZUH_MANAGER='10.0.3.103' \
        WAZUH_AGENT_GROUP='Debian' \
        WAZUH_AGENT_NAME='{{ ansible_hostname }}' \
        dpkg -i ./wazuh-agent_4.7.2-1_amd64.deb
      args:
        executable: /bin/bash

    - name: Reload systemd daemons (Linux)
      when: ansible_facts['os_family'] == 'Debian' and wazuh_installed_linux.stat.exists == false
      become: yes
      systemd:
        daemon_reload: yes

    - name: Activer le service Wazuh Agent au démarrage (Linux)
      when: ansible_facts['os_family'] == 'Debian' and wazuh_installed_linux.stat.exists == false
      become: yes
      systemd:
        name: wazuh-agent
        enabled: yes

    - name: Démarrer le service Wazuh Agent (Linux)
      when: ansible_facts['os_family'] == 'Debian' and wazuh_installed_linux.stat.exists == false
      become: yes
      systemd:
        name: wazuh-agent
        state: started
